### PR TITLE
Table redesign & admin pages reformatting

### PR DESCRIPTION
**Pull request by ahamelers**
Closes:

- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2297
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2008

I've checked and this is working on dev, but if you know of a better way to query for the submission date, please chime in!

### CODE REVIEW

**Comment by ryscher** [comment]
Thanks, Audrey. The tables look much better!

Yes, that seems like a good way to add the submission date to the dashboard -- I tested the mega query in the prod DB, and the new clause didn't add any noticeable delay.

One very small tweak: The pagination controls now have a bit of extra whitespace between them on the My datasets page. I don't think this was intentional, since they're still compact on the dashboard.
Screenshot 2023-02-21 at 12 58 19 PM

**Comment by sfisher** [comment]
This looks much cleaner than before.  I like it.  Interesting that the "my datasets" page now has a _show all_ link.  I think that is ok and most authors only have a few datasets, anyway.  though if you click the "show all" link then the "show pages" link to get back to a paged view is kind of squished up against the heading below.

Screenshot 2023-02-21 at 10 36 24 AM

Also seems like the "Get CSV" link below the paging is kind of squished up with it.

Screenshot 2023-02-21 at 10 36 56 AM

These are both very minor things, though.

**Review by sfisher — APPROVED** [review]
looks good to me aside from the couple of layout changes.  I haven't check all the pages that have tables with paging.  Maybe good to look through them all (mostly in the superuser tools, I think) just to be sure things all look good.

I like the alternating colors, too.

**Comment by ahamelers** [comment]
> One very small tweak: The pagination controls now have a bit of extra whitespace between them on the My datasets page. I don't think this was intentional, since they're still compact on the dashboard.

This was intentional but I _only_ really checked the pagination buttons on this page, which was a mistake 😬 

>  I haven't check all the pages that have tables with paging. Maybe good to look through them all (mostly in the superuser tools, I think) just to be sure things all look good.

I will do this! Thanks @ryscher and @sfisher

**Comment by ahamelers** [comment]
>  Interesting that the "my datasets" page now has a show all link

I didn't add this, but I may remove it as it's easier design wise, and most of our search results tables don't have this enabled

**Comment by ahamelers** [comment]
> Yes, that seems like a good way to add the submission date to the dashboard -- I tested the mega query in the prod DB, and the new clause didn't add any noticeable delay.

@ryscher , I just found that in the funder dashboard the following query is being done for the submission date, which is different but not really less complicated:

```sql
LEFT JOIN (SELECT identifier_id, MIN(stash_engine_resource_states.updated_at) init_sub_date
                      FROM stash_engine_resources
                      JOIN stash_engine_resource_states
                      ON stash_engine_resources.id = stash_engine_resource_states.resource_id
                      WHERE resource_state = 'submitted' GROUP BY identifier_id) as init_sub
            ON ids.id = init_sub.identifier_id
```

Is this finding the same date? Is either preferable?

Here's the query I wrote:

```sql
LEFT OUTER JOIN (SELECT DISTINCT sei.id, min(subcur.created_at) submission_date
            FROM stash_engine_identifiers sei
            RIGHT OUTER JOIN stash_engine_resources subser on sei.id = subser.identifier_id
            RIGHT OUTER JOIN stash_engine_curation_activities subcur on subser.id = subcur.resource_id
            WHERE subcur.status in ('submitted', 'peer-review')
            group by sei.id
          ) sd on sd.id = sei.id
```

Mine includes 'peer review' because of the description of SubmittedDate here: https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/technical_notes/dates.md

**Comment by ahamelers** [comment]
I've normalized styles for all the admin forms and buttons as well

**Pull request merged**
