### PR TITLE
Switch tenant to shibboleth authentication

### PR DESCRIPTION
**Pull request by ahamelers**
Closes https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2831

### CODE REVIEW

**Comment by sfisher** [comment]
I'm not sure if the shibboleth been verified to work by Fredonia yet (that it allows login and releasing of attributes), but the change looks good, otherwise.

**Comment by ahamelers** [comment]
Converting to a draft until confirmation it works on stage!

**Comment by ryscher** [comment]
Sarah is checking whether we need this update or whether they are happy with the current IP setup.

**Comment by ryscher** [comment]
Closing, since Fredonia is working fine with the existing setup.

**Pull request closed without merging**
