### PR TITLE
Change all the zenodo supplemental info back to software and tweaks

### PR DESCRIPTION
**Pull request by sfisher**
This PR is a copy of the zenodo-code branch with the following changes.

- main branch merged back in and manually resolved a bunch of merge conflicts (those are the commits you see older than the last week or so)
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1037
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1040
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1038
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1041
- The broken tests fixed for the changes (such as email, wording changes, MIT license, software instead of supplemental information, etc)
- I ran the tests locally and they are passing.

I hope this isn't too bad.  I deployed this branch on dev.  I hope helpful for testing.

### CODE REVIEW

**Review by ryscher — COMMENTED** [review]
Looks good. The vast majority of this has already been reviewed in other PRs. 

One minor issue: On the "Upload Data" page, the button at the bottom right goes to the
Review page, skipping "Upload Software". Is this intended?

**Comment by sfisher** [comment]
Probably not intended.  I'll go look at it and fix.  I must not have noticed and used the navigation at the top instead.  :-)

**Comment by sfisher** [comment]
Thanks for catching this, Ryan.  This was a problem only on the URL upload pages (not file upload) with the navigation and I put in a fix.  I went through both, but I guess I didn't look carefully enough when doing the URL uploads.

**Comment by ryscher** [comment]
Ok, thanks for all the work to get this working again!

**Pull request merged**
