### PR TITLE
Frictionless components

### PR DESCRIPTION
**Pull request by cacods**
This is a first result of displaying the frictionless validation report in a modal when the user clicks on "Issues found" in Tabular Data Check column. It's a simple modal, only with a close button and the frictionless-components styled report validation (so far with the frictionless-components own styles).

The frictionless-components javascript package uses Bootstrap CSS to build some styles, mainly to format the table view for the validation errors, to expand/collapse the details for the errors found and the for the font types. I just add the official Bootstrap CDN to access the Bootstrap styles, avoiding installing the whole Bootstrap into Dryad. We can decide if we will use Bootstrap to format the table and the collapsing/expanding part based in our wireframes/UI specifications besides our own styles and formatting.

### CODE REVIEW

**Comment by cacods** [comment]
I'm using React Styled components as an intermediary step for CSS page styles. Looks like there is some with that when running Jest tests. I'm going to solve that and make a new PR.

**Review by sfisher — APPROVED** [review]
This looks pretty good to me, Cassiano.  I think we can go ahead and merge it, yet before we release we'll have to fix some display issues.

I think the information page about validations looks pretty good, though.  Just other places it looks odd.

**Comment by sfisher** [comment]
I see some weird spacing and color changes because of bootstrap.

## This one is in yours with Bootstrap installed:
Screen Shot 2021-06-03 at 5 39 43 PM

----------

## This one is how it normally looks:
Screen Shot 2021-06-03 at 5 40 00 PM

----------

## This one with bootstrap and the button is falling off the edge:

Screen Shot 2021-06-03 at 5 56 34 PM

**Comment by cacods** [comment]
The frictionless-components package have their own css styles, so I forked the project and will add the new styles. I also will talk to Evgney from OKF for the possibility of merging my fork with the main project so all users can use it without Bootstrap CSS.

**Pull request merged**
