### PR TITLE
Reorderable funders, with new funding description field

### PR DESCRIPTION
**Pull request by ahamelers**
Closes https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2479, https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2475

### CODE REVIEW

**Review by sfisher — APPROVED** [review]
Thanks for adding the extra field and adding the reordering.  This works really well for me when I test it out and also the refactoring is good so it can be reused.

**Comment by ryscher** [comment]
Functionally, looks great. One minor edit: Instead of "Program/description", I would use "Program/division", since those are the most likely types of information that people will want to put in the box.

**Comment by ahamelers** [comment]
I've updated the label in the [associated branch](https://github.com/CDL-Dryad/dryad-app/tree/funder-entry), but it's not appearing in this pull request for some reason 🤔

**Comment by ahamelers** [comment]
I finally got it to appear by resetting the commit, committing it a second time, and force pushing. Pretty weird!

**Pull request merged**
