### PR TITLE
Add more granular edit highlighting to submission fields

### PR DESCRIPTION
**Pull request by ahamelers**
Closes https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2766

### CODE REVIEW

**Comment by sfisher** [comment]
I'm having a hard time remembering how to trigger this maybe.  I thought I saw this on the review page when I made changes in the past, or was it on the landing page?

in any case, I made some changes to a dataset and went to look at it and didn't see changes highlighted in either place.  I'm probably not looking exactly the right place or didn't take the correct steps first.

What are the suggested steps for testing this?

**Comment by ahamelers** [comment]
Change highlights appear on the review page:

1. When there is a "previously curated" (embargoed, action_required, published) version
2. Changes have been made from that previous version
3. And the user is a limited curator or up

**Comment by ryscher** [comment]
Generally, this looks good. But something is re-ordering the keywords, which throws off the highlight. In the screenshot below, I added the keywords "new" and "morenew":

Screenshot 2023-09-07 at 5 33 13 PM

**Comment by ahamelers** [comment]
Because of the reorderable authors and funders, I'd set highlighting based on the item index, to capture both new entries and reordering as changes. For the keywords in particular it's very easy to base the highlighting on the text content rather than the index.

**Comment by ryscher** [comment]
Thanks, that fixed the issue!

**Pull request merged**
